Chef manager retest
dislocated-su/ENG1-2 pull request #122
Opened 2023-05-02 19:36 UTC by Skuxa

Implement #77 after major rework.

2023-05-02 23:58 UTC, dislocated-su requested changes
You need to add javadoc comments and remove dangling commented out lines

2023-05-03 00:51 UTC, dislocated-su requested changes
Please remove commented out tests

2023-05-03 00:51 UTC, dislocated-su commented on tests/src/cs/eng1/tests/chef/ChefManagerTests.java
> +
Get rid of this

2023-05-03 00:51 UTC, dislocated-su commented on tests/src/cs/eng1/tests/customer/CustomerTests.java
> +    public void fulfillOrderTests() {}
Did we forget about this?

2023-05-03 00:51 UTC, dislocated-su commented on tests/src/cs/eng1/tests/stations/SubmitStationTests.java
> +    // stage,
bruh

2023-05-03 00:55 UTC, Skuxa commented on tests/src/cs/eng1/tests/customer/CustomerTests.java
> +    public void fulfillOrderTests() {}
yes

2023-05-03 00:55 UTC, Skuxa commented on tests/src/cs/eng1/tests/chef/ChefManagerTests.java
> +
yes

2023-05-03 00:55 UTC, Skuxa commented on tests/src/cs/eng1/tests/stations/SubmitStationTests.java
> +    // stage,
yes.

2023-05-03 00:57 UTC, dislocated-su approved these changes

2023-05-03 00:57 UTC, dislocated-su approved these changes
This good

2023-05-03 00:59 UTC, merged