Power Up Creation
dislocated-su/ENG1-2 pull request #70
Opened 2023-04-02 22:37 UTC by roh518

Closes #67

2023-04-20 13:37 UTC, dislocated-su requested changes
Haven't tested yet but had some questions while reading the code

2023-04-20 13:37 UTC, dislocated-su commented on core/src/cs/eng1/piazzapanic/PlayerState.java
> +    public static PlayerState getInstance() {
Would the Singleton pattern here mean that PlayerState can carry over multiple games? Like if I exit scenario mode and then enter endless?

2023-04-20 13:37 UTC, dislocated-su commented on core/src/cs/eng1/piazzapanic/screens/GameScreen.java
> +    // private final PowerUps powerUps;
Probably want to remove that

2023-04-20 13:37 UTC, dislocated-su commented on core/src/cs/eng1/piazzapanic/screens/GameScreen.java
> +        // powerUps = new PowerUps();
```suggestion
```

2023-04-20 13:57 UTC, dislocated-su commented on core/src/cs/eng1/piazzapanic/PlayerState.java
> +    public static PlayerState getInstance() {
I can that the PlayerState is reset.

2023-04-20 23:57 UTC, dislocated-su approved these changes

2023-04-21 12:28 UTC, LouisWarren approved these changes
lgtm

2023-04-21 12:39 UTC, merged